"""
Django settings for inventry_checker project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s&(4h_8cz*%4@@4-ph^h(pb9q#$*x_4!&=ul)3@=a=d$jt2mtp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'annotator',
    'get_imgs',
    'checker',
    'configuration',
    'crop_app',
    'training',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yolo_system.urls'
# ROOT_URLCONF = 'inventory_checker.urls'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'annotator/templates', 
            'get_imgs/templates', 
            'checker/templates', 
            'configuration/templates', 
            'crop_app/templates',
            'training/templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'yolo_system.asgi.application'
WSGI_APPLICATION = 'yolo_system.wsgi.application'
# ASGI_APPLICATION = 'inventry_checker.asgi.application'
# WSGI_APPLICATION = 'inventry_checker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja-jp'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'annotator/static/',
    BASE_DIR / 'checker/static/',
    BASE_DIR / 'configuration/static/',
    BASE_DIR / 'get_imgs/static/',
    BASE_DIR / 'crop_app/static/',
    BASE_DIR / 'training/static/',
    # os.path.join(BASE_DIR, 'static'),
]

# プロジェクト追加画面ではフォルダ単位で大量の画像を選択するため、Djangoのmultipart層のファイル数上限は無効化する。
# 画像種別や登録可否はconfiguration.add_project側で検証する。
DATA_UPLOAD_MAX_NUMBER_FILES = None

# Media files (User uploaded content)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# Project root directory
PROJECT_ROOT = BASE_DIR.parent

# 新しいプロジェクト別フォルダ構成
PROJECTS_DIR = PROJECT_ROOT / 'projects'

# プロジェクト別のパス生成用のヘルパー関数
def get_project_path(project_name, subfolder=''):
    """プロジェクト別のパス生成"""
    if subfolder:
        return PROJECTS_DIR / project_name / subfolder
    return PROJECTS_DIR / project_name

def get_active_project_path(subfolder=''):
    """アクティブプロジェクトのパス生成"""
    from get_imgs.models import DataCollectionProject
    try:
        active_project = DataCollectionProject.get_active_project()
        if active_project:
            return get_project_path(active_project.folder_name, subfolder)
    except:
        pass
    # フォールバック：デフォルトプロジェクトを使用
    return get_project_path(DEFAULT_PROJECT_NAME, subfolder)

# 下位互換性のため従来のパスも保持（デフォルトプロジェクト用）
DEFAULT_PROJECT_NAME = 'default_project'

# 1. データ収集（画像取得）- 新構造
DATA_COLLECTION_DIR = get_project_path(DEFAULT_PROJECT_NAME, 'data_collection')

# 2. 画像切り抜き - 新構造
CROP_PREPARATION_DIR = get_project_path(DEFAULT_PROJECT_NAME, 'crop_preparation')
CROP_PREPARATION_CROPPED_DIR = get_project_path(DEFAULT_PROJECT_NAME, 'cropped')

# 3. アノテーション - 新構造
ANNOTATION_DATA_DIR = get_project_path(DEFAULT_PROJECT_NAME, 'annotated')
# ANNOTATION_IMAGES_DIR = ANNOTATION_DATA_DIR / 'images'
# ANNOTATION_LABELS_DIR = ANNOTATION_DATA_DIR / 'labels'

# 4. 学習データ - 新構造
TRAINING_DATA_DIR = get_project_path(DEFAULT_PROJECT_NAME, 'training')

# 5. 実用データ - 新構造
PRODUCTION_DATA_DIR = get_project_path(DEFAULT_PROJECT_NAME, 'production')

# 下位互換性のため従来のパスも保持
BASE_IMAGES_DIR = DATA_COLLECTION_DIR  # 従来のbase_imagesを新構造にマップ
SNAPS_DIR = PROJECT_ROOT / 'snaps'  # 既存のsnapsフォルダも保持

# 従来の構造（削除予定だが、移行期間中は保持）
LEGACY_DATA_COLLECTION_DIR = PROJECT_ROOT / 'data_collection'
LEGACY_ANNOTATION_DATA_DIR = PROJECT_ROOT / 'annotation_data'
LEGACY_CROP_PREPARATION_DIR = PROJECT_ROOT / 'crop_preparation'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
